# This layer sets up to create a prod ready container
# A default build of this Dockerfile will result in this layer being included.
# First stage, build the custom JRE
FROM eclipse-temurin:21-jdk-jammy AS builder

# Install binutils, required by jlink
RUN apt-get update -y &&  \
    apt-get install -y binutils

# Build small JRE image
RUN $JAVA_HOME/bin/jlink \
         --verbose \
         --add-modules java.base,java.compiler,java.desktop,java.instrument,java.management,java.naming,java.net.http,java.prefs,java.rmi,java.scripting,java.security.jgss,java.sql,jdk.jfr,jdk.unsupported \
         --strip-debug \
         --no-man-pages \
         --no-header-files \
         --compress=2 \
         --output /optimized-jdk-21

# Second stage, Use the custom JRE and build the app image
FROM alpine:latest AS runner
# FROM ubuntu:22.04 AS runner

ENV JAVA_HOME=/opt/jdk/jdk-21
ENV PATH="${JAVA_HOME}/bin:${PATH}"

# copy JRE from the base image
COPY --from=builder /optimized-jdk-21 $JAVA_HOME

# Add app user
ARG APP_USER=javauser

# Create a user to run the application, don't run as root
RUN addgroup --system $APP_USER &&  adduser --system $APP_USER --ingroup $APP_USER --shell /bin/false

# Create the application directory
RUN mkdir /home/app && chown -R $APP_USER /home/app

WORKDIR /home/app

# RUN apt-get update && apt-get install -y dumb-init
RUN apk --no-cache add dumb-init && \
	rm -rf /var/cache/apk/*

RUN chown -R $APP_USER:$APP_USER /home/app